name: hung-yi-lee-ml
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - jupyterlab
  - notebook
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pillow
  - tqdm
  - pip:
      - gdown==5.2.0
      - kagglehub==1.0.1
      - torch==2.7.1
      - torchaudio==2.7.1
      - torchvision==0.22.1
      - wandb==0.20.1
